#!/bin/bash
############################################################################
# Basic Protection Script to Protect You GameServer Against DDoS Attacks
# Author: Sanjay Singh, Shaurya Shah
# DDoS.sh
############################################################################

# Update Your Log file path here ips
# Player IPs from log file generated by plugin
ips="`cat /server/cs/cstrike/addons/amxmodx/logs/current_players_ips.log 2>/dev/null`"

# Game Tracker IPs whitelisted
gtips="208.167.241.190,208.167.241.185,208.167.241.186,208.167.241.183,208.167.241.189,108.61.78.147,108.61.78.148,108.61.78.149,108.61.78.150"


# Add Player IPs to firewall
block(){
	iptables -A INPUT -s $ips -j ACCEPT
	iptables -A INPUT -s $gtips -j ACCEPT
	iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
	iptables -P INPUT DROP
	iptables -P FORWARD DROP
}

# Allow All Traffic if ddos ended
flush(){
	iptables -F
	iptables -X
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
}

# Main DDoS Function
while(true)
do
	bw=$(python3 bwtop -s)
	bwint=${bw%%.*}
	time=$(date +"%d.%m.%Y - %H:%M:%S")

	if [ "$bwint" -le 4000 ]; then
		continue
	else
		if [ "$ips" = "" ]; then
			echo "Time: $time || $bw KB/s Empty IP File | [ BLOCKED ]" >> ddos.log
			block
			continue
		else
			echo "Time: $time || $bw KB/s Incoming DDoS BLOCKED | [ BLOCKED ]" >> ddos.log
			block
			sleep 90
			echo "Time: $time || Allowing Traffic | [ FLUSHED ]" >> ddos.log
			flush
			continue
		fi
	fi
done
